"""
Tools that report to stock transfers involved in lab ISO preparation
to trac tool.

AAB
"""
from thelma.automation.tools.iso.base import StockRackLayout
from thelma.automation.tools.iso.lab.processing import _LabIsoWriterExecutorTool
from thelma.automation.tools.iso.tracreporting import IsoStockTransferReporter
from thelma.automation.tools.utils.base import VOLUME_CONVERSION_FACTOR
from thelma.automation.tools.utils.base import add_list_map_element
from thelma.automation.tools.utils.base import get_trimmed_string
from thelma.automation.tools.writers import CsvColumnParameters
from thelma.automation.tools.writers import CsvWriter
from thelma.models.container import Tube
from thelma.models.liquidtransfer import ExecutedWorklist


__docformat__ = 'reStructuredText en'

__all__ = ['LabIsoStockTransferReporter',
           'LabIsoStockTransferLogFileWriter']


class LabIsoStockTransferReporter(IsoStockTransferReporter):
    """
    A special stock ISO stock transfer reporter for lab ISOs and ISO jobs.

    **Return Value:** The log file as stream (arg 0) and comment (arg 1)
    """

    EXECUTOR_CLS = _LabIsoWriterExecutorTool

    def __init__(self, executor, **kw):
        """
        Constructor:

        :param executor: The executor tool (after run has been completed).
        :type executor: :class:`_LabIsoWriterExecutorTool`
        """
        IsoStockTransferReporter.__init__(self, executor=executor, **kw)

        #: The stock rack layouts mapped onto stock rack barcodes.
        self.__stock_rack_layouts = None

    def reset(self):
        IsoStockTransferReporter.reset(self)
        self.__stock_rack_layouts = None

    def _fetch_executor_data(self):
        IsoStockTransferReporter._fetch_executor_data(self)
        self.__stock_rack_layouts = self.executor.get_stock_rack_layouts()
        self._check_input_map_classes(self.__stock_rack_layouts,
                      'stock rack layout map', 'stock rack barcode', basestring,
                      'stock rack layout', StockRackLayout)

    def _get_log_file_writer(self):
        """
        By default, we use the :class:`StockTransferLogFileWriter`.
        """
        writer = LabIsoStockTransferLogFileWriter(log=self.log,
                            stock_rack_layouts=self.__stock_rack_layouts,
                            executed_worklists=self._executed_stock_worklists)
        return writer

    def _set_ticket_id(self):
        iso_request = self.executor.entity.iso_request
        self._ticket_number = iso_request.experiment_metadata.ticket_number

    def _get_sample_type_str(self):
        IsoStockTransferReporter._get_sample_type_str(self)

    def _get_rack_str(self):
        """
        The target racks are contained in the executed worklists.
        In case of jobs the plates cannot be sorted by ISOs though because
        the ISO label cannot always be parsed from the plate labels.
        """
        plates = set()
        for executed_worklist in self._executed_stock_worklists:
            for elt in executed_worklist:
                trg_rack = elt.target_container.rack.barcode
                plates.add(trg_rack)

        return 'Target plates: %s' % (self._get_joined_str(plates))


class LabIsoStockTransferLogFileWriter(CsvWriter):
    """
    Creates a log file after each stock transfer. The log file contains
    molecule designs, stock tube barcodes and volumes and the barcode and
    position in the target rack.

    **Return Value:** file stream (CSV format)
    """
    NAME = 'Stock Transfer Log File Writer'

    #: The index for the molecule design pool ID column.
    MOLECULE_DESIGN_POOL_INDEX = 0
    #: The header for the molecule design pool ID column.
    MOLECULE_DESIGN_POOL_HEADER = 'Molecule Design Pool ID'

    #: The index for the tube barcode column.
    TUBE_BARCODE_INDEX = 1
    #: The header for the tube barcode column.
    TUBE_BARCODE_HEADER = 'Stock Tube Barcode'

    #: The index for the volume column.
    VOLUME_INDEX = 2
    #: The header for the volume column.
    VOLUME_HEADER = 'Volume (ul)'

    #: The index for the target rack barcode column.
    TARGET_RACK_BARCODE_INDEX = 3
    #: The header for the target rack barcode column.
    TARGET_RACK_BARCODE_HEADER = 'Target Rack Barcode'

    #: The index for the target position column.
    TARGET_POSITION_INDEX = 4
    #: The header for the target position column.
    TARGET_POSITION_HEADER = 'Target Position'

    def __init__(self, log, stock_rack_layouts, executed_worklists):
        """
        Constructor:

        :param stock_rack_layouts: The stock rack layouts are required to
            fetch the pool for a transfer.
        :type stock_rack_layouts: :class:`StockRackLayout`

        :param executed_worklists: The stock transfer executed worklists that
            have been generated by the executor.
        :type executed_worklists: :class:`list`

        :param log: The log to write into.
        :type log: :class:`thelma.ThelmaLog`
        """
        CsvWriter.__init__(self, log=log)

        #: The executed worklists that have been generated by the executor
        #: (mapped onto transfer job indices).
        self.executed_worklists = executed_worklists
        #: The working layout containing the molecule design pool data.
        self.stock_rack_layouts = stock_rack_layouts

        #: Stores the values for the molecule design pool ID column.
        self.__pool_values = None
        #: Stores the values for the tube barcode column.
        self.__tube_barcode_values = None
        #: Stores the values for the volume column.
        self.__volume_values = None
        #: Stores the values for the target rack barcode column.
        self.__trg_rack_barcode_values = None
        #: Stores the values for the target position column.
        self.__trg_position_values = None

    def reset(self):
        """
        Resets all values except for the initialisation values.
        """
        CsvWriter.reset(self)
        self.__pool_values = []
        self.__tube_barcode_values = []
        self.__volume_values = []
        self.__trg_rack_barcode_values = []
        self.__trg_position_values = []

    def _init_column_map_list(self):
        """
        Creates the :attr:`_column_map_list`
        """
        self.add_info('Start log file generation ...')

        self.__check_input()
        if not self.has_errors(): self.__store_column_values()
        if not self.has_errors(): self.__generate_column_maps()

    def __check_input(self):
        """
        Checks the initialisation values.
        """
        self.add_debug('Check input values ...')

        self._check_input_list_classes('executed worklist',
                      self.executed_worklists, ExecutedWorklist)
        self._check_input_map_classes(self.stock_rack_layouts,
                      'stock rack layout map', 'stock rack barcode', basestring,
                      'stock rack layout', StockRackLayout)

    def __store_column_values(self):
        """
        Store the values for the columns.
        """
        self.add_debug('Store values ...')

        target_rack_map = dict()
        for ew in self.executed_worklists.values():
            for et in ew:
                target_rack_barcode = et.target_container.rack.barcode
                if not target_rack_map.has_key(target_rack_barcode):
                    target_rack_map[target_rack_barcode] = []
                target_rack_map[target_rack_barcode].append(et)

        well_containers = set()
        missing_layouts = []

        for target_rack_barcode in sorted(target_rack_map.keys()):

            executed_transfers = target_rack_map[target_rack_barcode]
            if not self.stock_rack_layouts.has_key(target_rack_barcode):
                missing_layouts.append(target_rack_barcode)
                continue
            layout = self.stock_rack_layouts[executed_transfers]
            pool_map = self.__get_sorted_executed_transfers(executed_transfers,
                                                    layout, target_rack_barcode)
            if self.has_errors(): break

            for pool_id in sorted(pool_map.keys()):
                ets = pool_map[pool_id]
                for et in ets:
                    self.__pool_values.append(get_trimmed_string(pool_id))
                    source_container = et.source_container
                    if not isinstance(source_container, Tube):
                        pos_label = et.planned_transfer.source_position.label
                        well_containers.add(pos_label)
                        continue
                    self.__tube_barcode_values.append(source_container.barcode)
                    volume = et.planned_transfer.volume \
                                                    * VOLUME_CONVERSION_FACTOR
                    self.__volume_values.append(get_trimmed_string(volume))
                    self.__trg_rack_barcode_values.append(target_rack_barcode)
                    self.__trg_position_values.append(
                                    et.planned_transfer.target_position.label)

        if len(well_containers) > 0:
            well_container_list = list(well_containers)
            well_container_list.sort()
            msg = 'Some source containers in the worklists are wells: %s!' \
                   % (well_container_list)
            self.add_error(msg)

    def __get_sorted_executed_transfers(self, executed_transfers,
                                        stock_rack_layout, rack_barcode):
        """
        Sorts the executed transfer of a worklist by molecule design pool ID.
        """
        pool_map = dict()
        no_pools = set()

        for et in executed_transfers:
            rack_pos = et.planned_liquid_transfer.source_position
            sr_pos = stock_rack_layout.get_working_position(rack_pos)
            if sr_pos is None:
                no_pools.add(rack_pos.label)
                continue
            pool_id = sr_pos.molecule_design_pool.id
            add_list_map_element(pool_map, pool_id, et)

        if len(no_pools) > 0:
            msg = 'Could not find molecule design pools for the following ' \
                  'source positions in rack %s: %s.' % (rack_barcode,
                  self._get_joined_str(no_pools, is_strs=False))
            self.add_error(msg)

        return pool_map

    def __generate_column_maps(self):
        """
        Initialises the CsvColumnParameters object for the
        :attr:`_column_map_list`.
        """
        pool_column = CsvColumnParameters(self.MOLECULE_DESIGN_POOL_INDEX,
                    self.MOLECULE_DESIGN_POOL_HEADER, self.__pool_values)
        tube_column = CsvColumnParameters(self.TUBE_BARCODE_INDEX,
                    self.TUBE_BARCODE_HEADER, self.__tube_barcode_values)
        volume_column = CsvColumnParameters(self.VOLUME_INDEX,
                    self.VOLUME_HEADER, self.__volume_values)
        rack_barcode_column = CsvColumnParameters(
                    self.TARGET_RACK_BARCODE_INDEX,
                    self.TARGET_RACK_BARCODE_HEADER,
                    self.__trg_rack_barcode_values)
        rack_position_column = CsvColumnParameters(self.TARGET_POSITION_INDEX,
                    self.TARGET_POSITION_HEADER, self.__trg_position_values)

        self._column_map_list = [pool_column, tube_column, volume_column,
                                 rack_barcode_column, rack_position_column]


